---
- name: create a temp directory
  file:
    path: "{{ ffmpeg_temp_path }}"
    state: directory

- name: download and unarchive to temp directory
  unarchive:
    src: "{{ffmpeg_url}}"
    dest: "{{ffmpeg_temp_path}}/"
    copy: no